version: '3'

services:
  # Database
  db:
    network_mode: bridge
    image: mysql:5.7
    ports:
      - '3307:3306'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  # phpmyadmin
  phpmyadmin:
    network_mode: bridge
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: 172.17.0.2
      MYSQL_ROOT_PASSWORD: password 
  # Wordpress
  wordpress:
    network_mode: bridge
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '8000:80'
    restart: always
    volumes:
      - ./wp-content/:/var/www/html/wp-content 
    environment:
      WORDPRESS_DB_HOST: 172.17.0.2
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
volumes:
  db_data:
